######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 1 03:19:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += datetime.h tweet.h twitdiag.h twiteng.h user.h
SOURCES += datetime.cpp main.cpp tweet.cpp twitdiag.cpp twiteng.cpp user.cpp
